import { toCsv } from "@localedb/core";
import type { DataRecord, DatasetKey } from "./datasets";
import { UsageError } from "./datasets";

export type Format = "json" | "json-min" | "csv" | "ts";

export const FORMATS: readonly Format[] = ["json", "json-min", "csv", "ts"];

export const EXTENSIONS: Record<Format, string> = { json: "json", "json-min": "json", csv: "csv", ts: "ts" };

export function resolveFormat(value: string | undefined, fallback: Format = "json"): Format {
  if (!value) return fallback;
  if (!FORMATS.includes(value as Format)) {
    throw new UsageError(`Unknown format "${value}". Use one of: ${FORMATS.join(", ")}.`);
  }
  return value as Format;
}

export interface Entry {
  code: string;
  record: DataRecord;
}

export interface SerializeOptions {
  dataset: DatasetKey;
  /** Dataset version, written into the generated TypeScript header. */
  dataVersion: string;
}

/**
 * JSON and CSV hold an array of records, like the export on localedb.org.
 * TypeScript holds an object keyed by code, typed `as const`.
 */
export function serialize(entries: Entry[], format: Format, { dataset, dataVersion }: SerializeOptions): string {
  const records = entries.map((entry) => entry.record);
  switch (format) {
    case "json":
      return `${JSON.stringify(records, null, 2)}\n`;
    case "json-min":
      return `${JSON.stringify(records)}\n`;
    case "csv":
      return `${toCsv(records)}\r\n`;
    case "ts": {
      const keyed = Object.fromEntries(entries.map((entry) => [entry.code, entry.record]));
      const typeName = `${dataset[0].toUpperCase()}${dataset.slice(1)}Code`;
      return [
        `// Generated by @localedb/cli from LocaleDB data v${dataVersion}. Do not edit by hand.`,
        "// Data licenses: https://github.com/ozkurkculer/localedb/blob/main/packages/core/NOTICE",
        "",
        `export const ${dataset} = ${JSON.stringify(keyed, null, 2)} as const;`,
        "",
        `export type ${typeName} = keyof typeof ${dataset};`,
        "",
      ].join("\n");
    }
  }
}
